name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  node-version:
    description: 'Node version'
    required: false
    default: '16'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: "node14.Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}